---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: build-only-ios

on: # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:

env:
  CGO_ENABLED: 1
  GOOS: ios
  GOARCH: arm64

jobs:
  build-only-ios:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          check-latest: true

      - run: printf '::notice ::%s\n' "$(go version)"

      - run: go mod download

      - run: go build -trimpath ./...

      - run: |
          go test -covermode=atomic -coverprofile=coverage.out -coverpkg=. .
          sed -i.bak "/compat\/cmd\//d; /compat\/golang\//d;" coverage.out
          rm -f *.bak

      # - uses: actions/upload-artifact@v3
      #  with:
      #     name: ios-build
      #     path: build/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          fail_ci_if_error: false
          files: ./coverage.out
          name: coverage-${{ env.GOOS }}
          token: ${{ secrets.CODECOV_TOKEN }}
